### ISSUE TITLE
Migrate to JSON API

### ISSUE THREAD

**Issue by samosfator** [samosfator/MODULE.OK#29]
```bash
java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
	at ua.samosfator.moduleok.Student.getName(Student.java:49)
	at ua.samosfator.moduleok.Student.<init>(Student.java:27)
	at ua.samosfator.moduleok.StudentKeeper.initStudent(StudentKeeper.java:22)
	at ua.samosfator.moduleok.StudentKeeper.forceInitAndGetCurrentStudent(StudentKeeper.java:17)
	at ua.samosfator.moduleok.MainActivity.lambda$initAndSetAccountInfo$6(MainActivity.java:83)
	at ua.samosfator.moduleok.MainActivity.access$lambda$0(MainActivity.java)
	at ua.samosfator.moduleok.MainActivity$$Lambda$2.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5221)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

```

**Comment by samosfator** [comment]
Moved all the parsing to remote server - [moduleok.appspot.com](https://github.com/samosfator/mod.tanet-api). App will be migrated to using new JSON API.
