### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference

### ISSUE THREAD

**Issue by vladholubiev** [samosfator/MODULE.OK#45]
``` bash
java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
    at ua.samosfator.moduleok.student_bean.Subject.getLastModule(Subject.java:41)
    at ua.samosfator.moduleok.fragment.last_and_total.SubjectItemAdapter.lambda$new$8(SubjectItemAdapter.java:30)
    at ua.samosfator.moduleok.fragment.last_and_total.SubjectItemAdapter.access$lambda$0(SubjectItemAdapter.java)
    at ua.samosfator.moduleok.fragment.last_and_total.SubjectItemAdapter$$Lambda$1.compare(Unknown Source)
    at java.util.TimSort.binarySort(TimSort.java:261)
    at java.util.TimSort.sort(TimSort.java:186)
    at java.util.TimSort.sort(TimSort.java:169)
    at java.util.Arrays.sort(Arrays.java:2010)
    at java.util.Collections.sort(Collections.java:1883)
    at ua.samosfator.moduleok.fragment.last_and_total.SubjectItemAdapter.<init>(SubjectItemAdapter.java:30)
    at ua.samosfator.moduleok.fragment.last_and_total.LastTotalFragment.initSectionAdapter(LastTotalFragment.java:57)
    at ua.samosfator.moduleok.fragment.last_and_total.LastTotalFragment.onCreateView(LastTotalFragment.java:51)
    at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
    at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
    at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:454)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:135)
    at android.app.ActivityThread.main(ActivityThread.java:5221)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

```

**Comment by samosfator** [comment]
Obsolete issue. The view is removed.
The time for a COMEBACK, @Bodiver

**Comment by Bodiver** [comment]
Here we are again!

**Comment by abhay7030** [comment]
zxcv
